name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/danyelgranzotti/kagun_backend:latest -f backend/Dockerfile backend
          docker push ghcr.io/danyelgranzotti/kagun_backend:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-app
          path: frontend/dist/

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build the app
        run: npm run build
        working-directory: frontend

      - name: Package the app
        run: npm run package
        working-directory: frontend

      - name: Zip artifact
        run: zip -r electron-app.zip dist/
        working-directory: frontend

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        with:
          tag_name: v1.0-${{ github.sha }}
          release_name: Release v1.0-${{ github.sha }}
          body: |
            Release notes for v1.0-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: frontend/electron-app.zip
          asset_name: electron-app.zip
          asset_content_type: application/zip

      - name: Upload Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: frontend/dist-electron/win-unpacked/
          asset_name: kagun-tattoo-setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
